### PR TITLE
MRG: A common PR of Prep pipeline

### PR DESCRIPTION
**Pull request by Nick3151**
A common PR of PREP pipeline
Major functionalities:
Find noisy channels
RemoveTrend
RobustReference
PerformReference
Fit() Style PREP pipeline

### CODE REVIEW

**Comment by adam2392** [comment]
It looks like the CI is failing. Can you confirm that your tests are succeeding locally, and if so, can you just make sure the travis.ci reflects all the packages that need to be installed?

You can add lines that do conda/pip install.

It should work from pyprep/, when I run: "pytest" basically. Should be a relatively quick fix, and then I'll review it then.

**Comment by Nick3151** [comment]
Okay I'll try to fix it

**Comment by yjmantilla** [comment]
I will be testing this along the week with our dataset and provide feedback.

**Comment by Nick3151** [comment]
@adam2392 I tried to fix the travis CI problem, I added Python 3.6, it seems like Python 3.6 built successfully but Python 2.7 didn't. could you have a look at the details?

**Comment by adam2392** [comment]
> @adam2392 I tried to fix the travis CI problem, I added Python 3.6, it seems like Python 3.6 built successfully but Python 2.7 didn't. could you have a look at the details?

Oh yeah that is fine. Python3.6+ has way more language features, that just aren't backwards compatible. I'll review this.

@sappelhoff is a complete move into Python3.6+ okay w/ you? Python2.7 has officially stopped being supported I believe by new years.

**Comment by adam2392** [comment]
@Nick3151 and @AamnaLawrence just to clarify, are the other 2 PRs important, or is this the main one that implements all the issues?

If so, can you close those other 2 PRs. If not, lmk what the differences are.

**Comment by AamnaLawrence** [comment]
@adam2392 This PR includes what was implemented in the other 2 individual PRs.

**Comment by sappelhoff** [comment]
> @sappelhoff is a complete move into Python3.6+ okay w/ you? Python2.7 has officially stopped being supported I believe by new years.

Yes, let's drop Python 2 support!

**Review by adam2392 — CHANGES_REQUESTED** [review]
1. For the fit(), perhaps return the "cleaned" raw data, instead of self? If I'm wrong, lmk. We can discuss.
2. I added a makefile, which you can run `make check` to determine if your formatting is correct, and if there is errors in your docstrings. 
- please run this to fix up your docstrings

3. The edf files are rather big, but I suppose it's fine to stick them in there. An issue we can address in the future is adding these dynamically using the MNE datasets API, so they don't sit on the repo itself. But this is fine for now.

Overall looks good and I ran things locally and things seem to work sufficiently.

**Comment by adam2392** [comment]
@AamnaLawrence , @Nick3151 : Please, git pull to get the changes I made and then proceed. Also, I'm not sure what's up, but test_findnoisychannels fails "sometimes".

**Comment by Nick3151** [comment]
> 1. For the fit(), perhaps return the "cleaned" raw data, instead of self? If I'm wrong, lmk. We can discuss.
>
As mentioned in PREP paper, PREP pipeline should 'Retain sufficient information to allow users to re-reference using another method or to undo interpolation of a particular channel, so I just added as much info into self, including cleaned raw data, bad channels before and after interpolation, 'true' reference signal, etc. These info are also stored in Matlab's PREP,  so users can get whatever they need from self. 
Does it make sense? @adam2392

**Comment by adam2392** [comment]
> > 1. For the fit(), perhaps return the "cleaned" raw data, instead of self? If I'm wrong, lmk. We can discuss.
> 
> As mentioned in PREP paper, PREP pipeline should 'Retain sufficient information to allow users to re-reference using another method or to undo interpolation of a particular channel, so I just added as much info into self, including cleaned raw data, bad channels before and after interpolation, 'true' reference signal, etc. These info are also stored in Matlab's PREP, so users can get whatever they need from self.
> Does it make sense? @adam2392

Okay fair and makes sense! sounds good. I like it then.

**Comment by adam2392** [comment]
I fixed some easy formatting issues for you and now make check runs w/o error on my local computer.

**Comment by adam2392** [comment]
Okay everything looks good except: 

```
_______________________________ test_basic_input _______________________________
    def test_basic_input():
        """Test Reference output data type"""
        raw_tmp = raw.copy()
        params = {"ref_chs": ch_names, "reref_chs": ch_names}
        reference = Reference(raw_tmp, params, ransac=False)
        raw_new = reference.perform_reference()
        assert type(reference.noisy_channels) == dict
        assert type(reference.noisy_channels_original) == dict
        assert type(reference.bad_before_interpolation) == list
        assert type(reference.reference_signal) == np.ndarray
        assert type(reference.interpolated_channels) == list
        assert type(reference.still_noisy_channels) == list
>       assert type(raw_new) == mne.io.edf.edf.RawEDF
E       AssertionError: assert <class 'pypre...ce.Reference'> == <class 'mne.i...f.edf.RawEDF'>
E         -<class 'pyprep.reference.Reference'>
E         +<class 'mne.io.edf.edf.RawEDF'>
```

Seems like something broke when someone tried something?

**Review by adam2392 — APPROVED** [review]

**Comment by yjmantilla** [comment]
Hi, three things:

- Pardon me, maybe I'm not understanding something but shouldn't 'frac_bad' default to 0.01 instead of 0.1 in find_noisy_channels.py?:
```
def find_bad_by_correlation(self, correlation_secs=1.0, correlation_threshold=0.4, frac_bad=0.1):
```

EDIT: Ahhh I saw the reason in the ipynb example:

>  Notes: we keep all the default parameter settings as described in PREP paper except one, the fraction of bad time windows (we change it from 0.01 to 0.1), because the EEG data is 60s long, which means it gots only 60 time windows. We think the algorithm will be too sensitive if using the default setting.

 
- I propose that the montage rather than the montage kind to be a parameter entering the PREP, Basically the only change would be in  PrepPipeline class:
```
def __init__(self, raw, prep_params, montage_kind="standard_1020", ransac=True,montageIn=None):
#code before
        #montage = mne.channels.read_montage(kind=montage_kind, ch_names=self.ch_names)
        if montageIn is None:
            montage = mne.channels.make_standard_montage(kind=montage_kind)
        else:
            montage = montageIn
        self.raw.set_montage(montage)
# code after
```
This is also helpful since read_montage is being deprecated https://github.com/mne-tools/mne-python/issues/6950

The change could also be implemented in the same way in the Noisydata class but it seems it is not being used anymore.

- Currently I'm testing the implementation on my data but I will wait until sunday so as to have more mature conclusions.

**Comment by adam2392** [comment]
> Hi, three things:
> 
> 
> * I propose that the montage rather than the montage kind to be a parameter entering the PREP, Basically the only change would be in  PrepPipeline class:
> 
> ```
> def __init__(self, raw, prep_params, montage_kind="standard_1020", ransac=True,montageIn=None):
> #code before
>         #montage = mne.channels.read_montage(kind=montage_kind, ch_names=self.ch_names)
>         if montageIn is None:
>             montage = mne.channels.make_standard_montage(kind=montage_kind)
>         else:
>             montage = montageIn
>         self.raw.set_montage(montage)
> # code after
> ```
> 
> This is also helpful since read_montage is being deprecated [mne-tools/mne-python#6950](https://github.com/mne-tools/mne-python/issues/6950)

I somewhat agree! Although if that is the case, I wonder if it should've been attached to the raw beforehand using `raw.set_montage(montage)`. If that is the case, really what is necessary is a `Attribute_Exception` if a montage is not set in the raw data structure passed in. Then have the example reflect that necessity.

Would you want to make an Issue/PR for this? @yjmantilla 

> The change could also be implemented in the same way in the Noisydata class but it seems it is not being used anymore.
> 
> * Currently I'm testing the implementation on my data but I will wait until sunday so as to have more mature conclusions.

Yes, as of now, we are basically scrapping this class, and leaving it in rn for basically backwards comparison and testing. @sappelhoff any thoughts so far?

**Comment by yjmantilla** [comment]
Hi @adam2392 , 

I'm unsure about where to put the issue. I know I can put it in the original @sappelhoff  repository  but I think it makes more sense to put it in here. The problem is: There is no issue tab in this repository. Looking a bit I found that basically for forks one needs to activate a setting for the issue tab to be available: https://stackoverflow.com/questions/16406180/is-there-a-way-to-add-issues-to-a-github-forked-repo-without-modifying-the-orig

NOTE: I will keep discussing this issues once I know where to put issues so as to not keep convoluting this conversation.

**Comment by adam2392** [comment]
> Hi @adam2392 ,
> 
> I'm unsure about where to put the issue. I know I can put it in the original @sappelhoff repository but I think it makes more sense to put it in here. The problem is: There is no issue tab in this repository. Looking a bit I found that basically for forks one needs to activate a setting for the issue tab to be available: https://stackoverflow.com/questions/16406180/is-there-a-way-to-add-issues-to-a-github-forked-repo-without-modifying-the-orig
> 
> NOTE: I will keep discussing this issues once I know where to put issues so as to not keep convoluting this conversation.

Sure I’ve added any issues tab.

**Pull request merged**
